export const LOGIN_ACTION = 'LOGIN';
export const ASYNCSTORAGE_ACTION = 'ASYNCSTORAGE';
export const LANGUAGES_ACTION = 'LANGUAGES';
export const LOGOUT_ACTION = 'LOGOUT';
export const BOOKS_ACTION = 'BOOKS';
export const IS_LOADING_ACTION = 'IS_LOADING';
export const ALERT_INFO_ACTION = 'ALERT_INFO_ACTION';
export const SEARCH_BAR_ACTION = 'SEARCH_BAR_ACTION';